name: Go Test

on:
  push:
    paths:
      - ".github/workflows/go-test.yml"
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"
  pull_request:
    paths:
      - ".github/workflows/go-test.yml"
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["oldstable", "stable"]
    name: Test on Go ${{ matrix.go }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Go Setup
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Go Module Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Go Dependencies
        run: make deps.download
      - name: Go Coverage
        run: make cover
      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: |
            **/coverage.*
